name: Run GTests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Miniconda
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          miniforge-variant: Miniforge3
          auto-update-conda: true
          use-mamba: true

    # 3. Build project
    - name: Build project
      run: |
        sed -i 's/^[[:space:]]*UseWebSpice = "false"/  UseWebSpice = "true"/'  ${CODEBUILD_SRC_DIR}/ISIS3/isis/IsisPreferences
        sed -i 's/^[[:space:]]*UseWebSpice = "false"/  UseWebSpice = "true"/'  ${CODEBUILD_SRC_DIR}/ISIS3/isis/TestPreferences
        cd recipe
        echo $ENCRYPTION_KEY | openssl enc -aes-256-cbc -d -in kakadu/kakadu_7_9.zip.enc -out kakadu/kakadu_7_9.zip -pbkdf2 -iter 10000 -pass stdin
        unzip -j kakadu/kakadu_7_9.zip -d /tmp/kakadu_7_9 -x "__MACOSX/*"
        mkdir build
        cd build
        cp ${CODEBUILD_SRC_DIR}/ISIS3/isis/IsisPreferences ${CODEBUILD_SRC_DIR}/ISIS3/build/
        cp ${CODEBUILD_SRC_DIR}/ISIS3/isis/TestPreferences ${CODEBUILD_SRC_DIR}/ISIS3/build/
        cmake -GNinja -DJP2KFLAG=ON -DKAKADU_INCLUDE_DIR=/tmp/kakadu_7_9 ../isis
        ninja -j8

    # 4. Run gtests
    - name: Run tests
      run: |
        cd build
        ctest -j8 --output-on-failure --output-junit test-report.xml

    # 5. Upload test results
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: gtest-report
        path: build/test-report.xml
