name: Run GTests

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # 2. Set up Miniconda
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: isis
        python-version: 3.12              

    # 3. Build project
    - name: Build project
      env:
        ENCRYPTION_KEY: ${{ secrets.KDU_ENC_KEY }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate isis
        sed -i 's/^[[:space:]]*UseWebSpice = "false"/  UseWebSpice = "true"/'  ${GITHUB_WORKSPACE}/isis/IsisPreferences
        sed -i 's/^[[:space:]]*UseWebSpice = "false"/  UseWebSpice = "true"/'  ${GITHUB_WORKSPACE}/isis/TestPreferences
        cd recipe
        echo $ENCRYPTION_KEY | openssl enc -aes-256-cbc -d -in kakadu/kakadu_7_9.zip.enc -out kakadu/kakadu_7_9.zip -pbkdf2 -iter 10000 -pass stdin
        unzip -j kakadu/kakadu_7_9.zip -d /tmp/kakadu_7_9 -x "__MACOSX/*"
        cd ../
        mkdir build && cd build
        export ISISROOT=${GITHUB_WORKSPACE}/build
        cmake -GNinja -DJP2KFLAG=ON -DKAKADU_INCLUDE_DIR=/tmp/kakadu_7_9 ../isis
        ninja -j8

    # 4. Run gtests
    - name: Run tests
      run: |
        export ISISROOT=${GITHUB_WORKSPACE}/build
        source $CONDA/etc/profile.d/conda.sh
        conda activate isis
        export ISISROOT=${GITHUB_WORKSPACE}/build
        cd build
        ctest -R '.' -E '(_app_|_unit_|_module_)' -j 8 --output-on-failure --timeout 1800 --output-junit test-report.xml

    # 5. Upload test results
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: gtest-report
        path: build/test-report.xml
